# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

    jobs:
      - deployment:
        pool:
          vmImage: "ubuntu-latest"
        environment: docs-dev
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AmazonWebServices.aws-vsts-tools.S3Upload.S3Upload@1
                  inputs:
                    awsCredentials: "s3-autodoc.plantanapp.com"
                    regionName: "us-east-1"
                    bucketName: "learn-dev.plantanapp.com"
                    sourceFolder: "./"
                    globExpressions: "**"
                    logRequest: true
                    logResponse: true
                - task: AWSCLI@1
                  inputs:
                    awsCredentials: "s3-autodoc.plantanapp.com"
                    regionName: "us-east-1"
                    awsCommand: "cloudfront"
                    awsSubCommand: "create-invalidation"
                    awsArguments: '--distribution-id $(DistributionId) --paths "/*"'
                  displayName: "Invalidate CloudFront Cache"
